#!/usr/bin/env bash
# The redirection must be a “301 Moved Permanently”

sudo apt-get update
sudo apt-get -y install nginx
echo "Holberton School" >> /var/www/html/index.html
sed -i '/20i rewrite ^/redirect_me$ https://www.linkedin.com/;\n' /etc/nginx/sites-available/default
sudo service nginx start
