#!/usr/bin/env bash
# HTTP requests

sudo apt-get update
sudo apt-get -y install nginx
echo "Holberton School" >> /var/www/html/index.html
sed -i "21i \tadd_header X-Served-By $HOSTNAME;\n" /etc/nginx/nginx.conf
sudo service nginx start
