#!/usr/bin/env bash
# Load balancer for two servers
apt-get install software-properties-common
add-apt-repository ppa:vbernat/haproxy-1.6
apt-get update
apt-get install haproxy=1.6.\*
sed -i '/sendfile on;/a 
frontend haproxynode
	bind *:80
	mode http
	default_backend backendnodes

backend backendnodes
	balance roundrobin
	server 1306-web-01 35.227.22.206:80 check
	server 1306-web-02 34.235.89.220:80 check
' /etc/haproxy/haproxy.cfg 
sudo service haproxy restart
