#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 100.
# Displays FizzBuzz when the number is a multiple of 3 and 5
# Displays Fizz when the number is multiple of 3
# Displays Buzz when the number is a multiple of 5
# Otherwise, displays the number In a list format

for((var = 1; var <= 100; var++))
do
    if [ $((var%5)) == 0 ] && [ $((var%3)) == 0 ]
    then
        echo "FizzBuzz"
    elif [ $((var%3)) == 0 ]
    then
        echo "Fizz"
    elif [ $((var%5)) == 0 ]
    then
        echo "Buzz"
    else
        echo "$var"
    fi
done
