#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times,
# but for the 9th iteration, displays Holberton School
# and then Hi on a new line
i=0
j=10
while [ $i -lt $j ]
do
    if [ $i -eq 9 ]
    then
        echo "Hi"
    fi
    echo "Holberton School"
    i=$((i+1))
done
